---
- name: set apt proxy
  template:
    src: templates/00apt-cacher-proxy.template
    dest: /etc/apt/apt.conf.d/00apt-cacher-proxy
    owner: root
    group: root
    mode: '0644'

- name: add apt_keys via file for additional repositories
  apt_key:
    data: "{{ item.gpgkey_file }}"
    state: present
  with_items: "{{ repos }}"
  when: item.gpgkey_file is defined

- name: add apt_keys via id for additional repositories
  apt_key:
    data: "{{ item.gpgkey_id }}"
    state: present
  with_items: "{{ repos }}"
  when: item.gpgkey_id is defined

- name: add additional repositories to sources.list.d
  apt_repository:
    repo: "deb {{ item.uri }} {{ item.suite }} {{ item.components }}"
    filename: "{{ item.label }}"
    state: present
    validate_certs: no
    update_cache: no
  with_items: "{{ repos }}"

- name: Run "apt-get update"
  apt:
    update_cache: yes

- name: dist-upgrade (if in build chroot)
  apt:
    upgrade: dist
  when: chrooted
