---
- name: Install packages (excluding Recommends)
  apt:
    state: present
    update_cache: no
    install_recommends: no
    name: [ 'apparmor',
            'apport',
            'apport-symptoms',
            'apt-clone',
            #'apt-transport-https',
            'apt-utils',
            'apturl-common',
            'at-spi2-core',
            'avahi-utils',
            'bash-completion',
            'bind9-dnsutils',
            'bind9-host',
            'ca-certificates',
            'cracklib-runtime',
            'cryptsetup',
            'cryptsetup-bin',
            'enchant',
            'fuse',
            'glabels',
            'glabels-data',
            'geoip-database',
            'ifupdown',
            'iputils-tracepath',
            'iputils-arping',
            'iputils-ping',
            'isc-dhcp-common',
            'javascript-common',
            'libnss-mdns',
            'libnss3',
            'libpaper-utils',
            'libwmf-bin',
            'lz4',
            'ntpdate',
            'openssl',
            'pdfarranger',
            'python3-systemd',
            'rdate',
            'rsyslog',
            'rsync',
            #'scite',
            'tcpdump',
            'ubuntu-minimal',
            'ubuntu-standard',
            'ufw',
            'unp',
            'xdg-user-dirs' ]

- name: Install filesystem support packages (excluding Recommends)
  apt:
    state: present
    update_cache: no
    install_recommends: no
    name: [ 'dosfstools',
            'dvd+rw-tools',
            'e2fslibs:amd64',
            'e2fsprogs',
            'ecryptfs-utils',
            'exfat-fuse',
            'exfat-utils',
            'gdisk',
            'gvfs-bin',
            'gvfs-backends',
            'gvfs-fuse',
            'jfsutils',
            'lvm2',
            'ntfs-3g',
            'reiserfsprogs',
            'xfsprogs' ]

- name: Install extra util packages (excluding Recommends)
  apt:
    state: present
    update_cache: no
    install_recommends: no
    name: [ 'appstream',
            'apturl',
            'bc',
            'ca-certificates',
            'debconf-i18n',
            'dirmngr',
            'espeak-ng-data',
            'espeak-ng-data:amd64',
            #'gir1.2-accountsservice-1.0',
            #'gir1.2-appindicator3-0.1',
            #'gir1.2-atk-1.0',
            #'gir1.2-atspi-2.0',
            #'gir1.2-caribou-1.0',
            #'gir1.2-clutter-1.0',
            #'gir1.2-cogl-1.0',
            #'gir1.2-coglpango-1.0',
            #'gir1.2-dbusmenu-glib-0.4',
            #'gir1.2-dee-1.0',
            #'gir1.2-freedesktop',
            #'gir1.2-gck-1',
            #'gir1.2-gcr-3',
            #'gir1.2-gdesktopenums-3.0',
            #'gir1.2-gdkpixbuf-2.0',
            #'gir1.2-gdm-1.0',
            #'gir1.2-geoclue-2.0',
            #'gir1.2-geocodeglib-1.0',
            #'gir1.2-glib-2.0',
            #'gir1.2-gnomebluetooth-1.0',
            #'gir1.2-gnomedesktop-3.0',
            #'gir1.2-gnomekeyring-1.0',
            #'gir1.2-gst-plugins-base-1.0',
            #'gir1.2-gstreamer-1.0',
            #'gir1.2-gtk-3.0',
            #'gir1.2-gtksource-3.0',
            #'gir1.2-gudev-1.0',
            #'gir1.2-gweather-3.0',
            #'gir1.2-ibus-1.0',
            #'gir1.2-javascriptcoregtk-4.0',
            #'gir1.2-json-1.0',
            #'gir1.2-networkmanager-1.0',
            #'gir1.2-nm-1.0',
            #'gir1.2-nma-1.0',
            #'gir1.2-nmgtk-1.0',
            #'gir1.2-notify-0.7',
            #'gir1.2-packagekitglib-1.0',
            #'gir1.2-pango-1.0',
            #'gir1.2-peas-1.0',
            #'gir1.2-polkit-1.0',
            #'gir1.2-rb-3.0',
            #'gir1.2-rsvg-2.0',
            #'gir1.2-secret-1',
            #'gir1.2-soup-2.4',
            #'gir1.2-timezonemap-1.0',
            #'gir1.2-totem-1.0',
            #'gir1.2-totem-plparser-1.0',
            #'gir1.2-udisks-2.0',
            #'gir1.2-unity-5.0',
            #'gir1.2-upowerglib-1.0',
            #'gir1.2-vte-2.91',
            #'gir1.2-webkit2-4.0',
            #'gir1.2-wnck-3.0',
            #'gir1.2-xkl-1.0',
            'gnupg',
            'gnupg-agent',
            'gnupg-l10n',
            'gstreamer1.0-alsa',
            'gstreamer1.0-clutter-3.0',
            'gstreamer1.0-packagekit',
            'gstreamer1.0-plugins-base-apps',
            'gstreamer1.0-tools',
            'gstreamer1.0-plugins-base',
            'gstreamer1.0-plugins-good',
            'gstreamer1.0-pulseaudio',
            'gstreamer1.0-x',
            'htop',
            'imagemagick',
            'imagemagick-6.q16',
            'iptables',
            'krb5-locales',
            'libabw-0.1-1',
            'libart-2.0-2',
            'libatm1',
            'libauthen-sasl-perl',
            'libcairo-perl',
            'libclucene-contribs1v5',
            'libclucene-core1v5',
            'libcmis-0.5-5v5',
            'libcogl-common',
            'libdvdnav4',
            'libe-book-0.1-1',
            'libeot0',
            'libetonyek-0.1-1',
            'libexttextcat-2.0-0',
            'libfreehand-0.1-1',
            'libgail18',
            'libgail-common',
            'libglib-perl',
            'libgpgmepp6',
            'libhtml-format-perl',
            'libhtml-form-perl',
            'libmagickcore-6.q16-2-extra',
            'libmhash2',
            'libneon27-gnutls',
            'libnet-libidn-perl',
            'libnss-myhostname',
            'libodfgen-0.1-1',
            'libotf0',
            'libpagemaker-0.0-0',
            'libpam-cap',
            'libperlio-gzip-perl',
            'libqt5svg5',
            'librevenge-0.0-0',
            'libtie-ixhash-perl',
            'libwavpack1',
            'libxml-parser-perl',
            'libxml-twig-perl',
            'libxml-xpathengine-perl',
            'logrotate',
            'lp-solve',
            'lupin-casper',
            'mtr-tiny',
            'p7zip',
            'packagekit',
            'packagekit-tools',
            'peek',
            'perl',
            'perl-modules',
            'popularity-contest',
            'publicsuffix',
            'python',
            'python3-icu',
            'python3-keyring',
            'python3-keyrings.alt',
            'python3-launchpadlib',
            'python3-lazr.restfulclient',
            'python3-lazr.uri',
            'python3-oauth',
            'python3-pam',
            'python3-renderpm',
            'python3-secretstorage',
            'python3-simplejson',
            'python3-uno',
            'python3-wadllib',
            'python3-zope.interface',
            'python-gobject-2',
            'samba-common-bin',
            'samba-libs',
            'sgml-base',
            't1utils',
            'tcpd',
            'unzip',
            'whoopsie',
            'xdg-utils',
            'xml-core',
            'xterm',
            'zip' ]
     
- name: Install restricted addons (codecs etc)
  apt:
    state: present
    update_cache: no
    install_recommends: no
    name: [ 'chromium-codecs-ffmpeg-extra',
            'gstreamer1.0-libav',
            'gstreamer1.0-plugins-ugly',
            'gstreamer1.0-vaapi' ]

- name: Install Rob G packages
  apt:
    state: present
    update_cache: no
    install_recommends: no
    name: [ 'glew-utils',
            'javascript-common',
            'mdbtools',
            'wmctrl' ]
