---
- name: debconf preseeding
  debconf: 
    name: "{{ item.p }}"
    question: "{{ item.q }}"
    vtype: "{{ item.vt }}"
    value: "{{ item.val }}"
  with_items:
    - { p: "openssh-server",
        q: "openssh-server/permit-root-login", 
        vt: "boolean", 
        val: "true" 
      }
    - { p: "unattended-upgrades",
        q: "unattended-upgrades/enable_auto_updates", 
        vt: "boolean", 
        val: "false" 
      }
